var data = {
	"Noticia":[
		{"Titulo":"Índios fazem 'oração' em frente ao STF durante julgamento sobre direito a terras","Link":"http://g1.globo.com/distrito-federal/noticia/indios-fazem-oracao-em-frente-a-stf-durante-julgamento-sobre-direito-a-terras.ghtml","Comentarios":["Índio tem que tá no mato correndo atrás de bicho", "Muito me engano, ou tem um índio de bigode na foto acima...mais falso que whisk paraguaio! kkkk", "Bando de selvagens...o Temmer tem de mandar o exército descer a madeira nesses nativos, isso sim! Para que serve um Índio, que nem votar, vota?"]},
		{"Titulo":"Laudo confirma que restos mortais encontrados dentro de jacaré são de humanos","Link":"http://g1.globo.com/to/tocantins/noticia/laudo-confirma-que-restos-mortais-encontrados-dentro-de-jacare-sao-de-humanos.ghtml","Comentarios":["Matar o animal, quanta imbecilidade!", "O jacaré é apenas uma vítima da sociedade racista, elitista, machista, misógina, trânsfoba e homófoba.", "A culpa é do P T com a campanha do desarmamento !!!", "mais ainda acho meno perigoso dormir do lado de jacaré do que dormir do lado de uma mulher com TPM", "O jacare comeu o rapaz? Que coisa! Nem um jantarzinho antes?"]},
		{"Titulo":"STJ mantém condenação de Bolsonaro por ofensas a Maria do Rosário","Link":"http://g1.globo.com/politica/noticia/stj-mantem-condenacao-de-bolsonaro-por-ofensas-a-maria-do-rosario.ghtml","Comentarios":["Afinal, ela MERECE ou NÃO MERECE????", "Vou com o mito !", "Bol'sonaro vai salvar o Brasil dos ban'didos!!!", "O P'T foi a doença do Brasil mas o Bol'sonaro será a cura!!"]},
		{"Titulo":"Post de Obama após Charlottesville se torna o mais curtido da história do Twitter","Link":"http://g1.globo.com/mundo/noticia/mensagem-de-obama-apos-charlottesvile-se-torna-segundo-tuite-mais-curtido-da-historia-do-twitter.ghtml","Comentarios":["Nelson Mandela, terrorista que queimava pessoas em pneus!!!! Que lindo!!! M í d i a sociais são todas controladas pela esquerda.......acredito em Papai Noel menos em curtidas no Twiiter.........Twiiter, Facebook e Google CREDIBILIDADE = 0", "Eu não gostei do filme do planeta dos macacos. Achei muito sem ação esse último. O segundo foi o melhor, não há dúvidas.", "Eu queria se livrar do racismo dentro de mim, mas não consigo... Lamentavel !!!", "Comunista o que você fez pela Síria ?"]},
		{"Titulo":"Ex-executivo de SC que vive em aeroporto do RJ consegue emprego: 'obrigado a todos'","Link":"http://g1.globo.com/sc/santa-catarina/noticia/ex-executivo-de-sc-que-vive-em-aeroporto-do-rj-consegue-emprego-obrigado-a-todos.ghtml","Comentarios":["Se tivesse estudado já mais passaria por isso. Mas a preguiça falou mais alto. Paga-se impostos altos para o banco da praça servir de cama . Absurdo.", "Se ele fosse um jogador de futebol ou um político estaria imune a esse problema que passou! Isso é Brasil, amigos!", "Esse é o Brasil de Temer......... Tememos muito senhor presidente...."]},
		{"Titulo":"Alexandre Frota tem conta suspensa no Twitter","Link":"http://g1.globo.com/tecnologia/noticia/alexandre-frota-tem-conta-suspensa-no-twitter.ghtml","Comentarios":["Pseudo esquerda caviar é o câncer do Brasil", "Todos esses grandes capitalistas que dominam o mundo hoje são de esquerda.", "Fora PT. Fora Maduro! Foro Foro de SP!"]},
		{"Titulo":"Venezuela liberta violinista que se tornou símbolo de protestos","Link":"http://g1.globo.com/mundo/noticia/venezuela-liberta-violinista-que-se-tornou-simbolo-de-protestos.ghtml","Comentarios":["Agora pode tocar aquela do Raul...", "Esse é o tal \"excesso de democracia\" que a esquerda mortadela quer implementar no Brasil."]},
		{"Titulo":"Por que ter filhos prejudica mulheres e favorece pais no mercado de trabalho","Link":"http://g1.globo.com/economia/concursos-e-emprego/noticia/por-que-ter-filhos-prejudica-mulheres-e-favorece-pais-no-mercado-de-trabalho.ghtml","Comentarios":["Querem que fiquemos gravidos. Jamais! Isso é coisa pro Pabllo e para o Jean ui ui ."]}
	]
}
		
//{"Titulo":"","Link":"","Comentarios":[""]}